### PR TITLE
Render comments as markdown

### PR DESCRIPTION
**Pull request by Kobzol**
When reviewing tasks, I often need to include snippets of code. Currently, it looks terrible, as there is no formatting.
This PR changes comments to be rendered with markdown. It also sanitizes the output, since comments can also be entered by untrusted users.

If you agree with it, I would also like to add some basic syntax highlighting (`highlight.js`).

### CODE REVIEW

**Comment by Kobzol** [comment]
It looks like this:
image

**Comment by brabemi** [comment]
Pokusím se na to do konce měsíce podívat

**Comment by Kobzol** [comment]
Ok :) Druhá možnost implementace by byla posílat to z backendu tak, jak to leží a běží v DB, ale na frontendu použít něco jako https://github.com/remarkjs/react-markdown.

**Comment by frenzymadness** [comment]
Comments now contain html tags.

**Comment by Kobzol** [comment]
Forced refresh of the page (Ctrl + Shift + R in Chrome, depends on the browser) should fix it.

**Pull request merged**
